import { 
  ISPProvider, 
  ISPPlan, 
  Location, 
  RechargeTransaction,
  NotificationTemplate
} from './types';

export const MOCK_PROVIDERS: ISPProvider[] = [
  { id: 'P-001', name: 'Airtel Fiber', supportContact: '121', portalUrl: 'https://www.airtel.in/broadband' },
  { id: 'P-002', name: 'Jio Fiber', supportContact: '1800-889-9999', portalUrl: 'https://www.jio.com/fiber' },
  { id: 'P-003', name: 'ACT Fibernet', supportContact: '080-42840000', portalUrl: 'https://www.actcorp.in' },
  { id: 'P-004', name: 'BSNL Bharat Fiber', supportContact: '1800-345-1500', portalUrl: 'https://portal.bsnl.in' },
];

export const MOCK_PLANS: ISPPlan[] = [
  { id: 'PL-001', providerId: 'P-001', name: 'Entertainment 200Mbps', bandwidth: '200 Mbps', amount: 999, billingCycle: 'Monthly' },
  { id: 'PL-002', providerId: 'P-001', name: 'Professional 300Mbps', bandwidth: '300 Mbps', amount: 1499, billingCycle: 'Monthly' },
  { id: 'PL-003', providerId: 'P-002', name: 'Jio 100Mbps Unlimited', bandwidth: '100 Mbps', amount: 699, billingCycle: 'Monthly' },
  { id: 'PL-004', providerId: 'P-003', name: 'ACT Storm', bandwidth: '300 Mbps', amount: 1085, billingCycle: 'Monthly' },
];

export const MOCK_LOCATIONS: Location[] = [
  {
    id: 'LOC-101',
    name: 'Bengaluru HSR Store',
    branchType: 'Store',
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'IN',
    ispProviderId: 'P-001',
    connectionType: 'FTTH',
    planId: 'PL-001',
    bandwidth: '200 Mbps',
    amount: 999,
    billingCycle: 'Monthly',
    lastRechargeDate: '2026-03-15',
    nextDueDate: '2026-04-15',
    daysRemaining: 14,
    accountId: '1029384756',
    registeredMobile: '9876543210',
    registeredEmail: 'hsr.store@mizaj.com',
    paymentMode: 'UPI',
    autoPay: false,
    status: 'Active',
    contactPerson: 'Arjun K',
    adminOwner: 'HO-IT-01',
    priority: 'High',
    criticality: 'High',
    backupAvailable: true,
  },
  {
    id: 'LOC-102',
    name: 'Mumbai Warehouse A',
    branchType: 'Warehouse',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'IN',
    ispProviderId: 'P-002',
    connectionType: 'Leased Line',
    planId: 'PL-003',
    bandwidth: '100 Mbps',
    amount: 699,
    billingCycle: 'Monthly',
    lastRechargeDate: '2026-03-01',
    nextDueDate: '2026-04-01',
    daysRemaining: 0,
    accountId: '8877665544',
    registeredMobile: '9123456789',
    registeredEmail: 'mumbai.wh@mizaj.com',
    paymentMode: 'Net Banking',
    autoPay: true,
    status: 'Due Soon',
    contactPerson: 'Suresh M',
    adminOwner: 'HO-IT-02',
    priority: 'Medium',
    criticality: 'High',
    backupAvailable: false,
  },
  {
    id: 'LOC-103',
    name: 'Delhi Corporate Office',
    branchType: 'Office',
    city: 'New Delhi',
    state: 'Delhi',
    country: 'IN',
    ispProviderId: 'P-003',
    connectionType: 'FTTH',
    planId: 'PL-004',
    bandwidth: '300 Mbps',
    amount: 1085,
    billingCycle: 'Monthly',
    lastRechargeDate: '2026-02-25',
    nextDueDate: '2026-03-25',
    daysRemaining: -7,
    accountId: 'ACT-DEL-9921',
    registeredMobile: '9988776655',
    registeredEmail: 'delhi.hq@mizaj.com',
    paymentMode: 'Corporate Card',
    autoPay: false,
    status: 'Overdue',
    contactPerson: 'Neha S',
    adminOwner: 'HO-IT-01',
    priority: 'High',
    criticality: 'High',
    backupAvailable: true,
  },
  {
    id: 'LOC-104',
    name: 'Chennai Factory 01',
    branchType: 'Factory',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'IN',
    ispProviderId: 'P-004',
    connectionType: 'Broadband',
    planId: 'PL-001',
    bandwidth: '100 Mbps',
    amount: 850,
    billingCycle: 'Quarterly',
    lastRechargeDate: '2026-01-10',
    nextDueDate: '2026-04-10',
    daysRemaining: 9,
    accountId: 'BSNL-CH-4432',
    registeredMobile: '8877665544',
    registeredEmail: 'chennai.fac@mizaj.com',
    paymentMode: 'Cash',
    autoPay: false,
    status: 'Active',
    contactPerson: 'Venkatesh R',
    adminOwner: 'HO-IT-03',
    priority: 'Low',
    criticality: 'Medium',
    backupAvailable: false,
  }
];

export const MOCK_RECHARGES: RechargeTransaction[] = [
  {
    id: 'TXN-001',
    locationId: 'LOC-101',
    amount: 999,
    tax: 179.82,
    total: 1178.82,
    rechargeDate: '2026-03-15',
    validUntil: '2026-04-15',
    paymentMode: 'UPI',
    paymentStatus: 'Success',
    transactionId: 'UPI1234567890',
    bankReference: 'UTR1234567890',
    gatewayName: 'Razorpay',
    settlementStatus: 'Settled',
    initiatedBy: 'HO-IT-01',
    remarks: 'Monthly renewal',
  },
  {
    id: 'TXN-002',
    locationId: 'LOC-103',
    amount: 1085,
    tax: 195.30,
    total: 1280.30,
    rechargeDate: '2026-02-25',
    validUntil: '2026-03-25',
    paymentMode: 'Credit Card',
    paymentStatus: 'Success',
    transactionId: 'CC-998877',
    bankReference: 'REF-998877',
    gatewayName: 'PhonePe PG',
    settlementStatus: 'Settled',
    initiatedBy: 'HO-IT-01',
    remarks: 'Corporate card payment',
  },
  {
    id: 'TXN-003',
    locationId: 'LOC-102',
    amount: 699,
    tax: 125.82,
    total: 824.82,
    rechargeDate: '2026-04-01',
    validUntil: '2026-05-01',
    paymentMode: 'Net Banking',
    paymentStatus: 'Pending Approval',
    transactionId: 'NB-776655',
    bankReference: 'UTR776655',
    gatewayName: 'Manual',
    settlementStatus: 'Unsettled',
    initiatedBy: 'HO-IT-02',
    remarks: 'Waiting for bank confirmation',
  }
];

export const REVENUE_DATA = [
  { name: 'Jan', revenue: 125000 },
  { name: 'Feb', revenue: 132000 },
  { name: 'Mar', revenue: 148000 },
  { name: 'Apr', revenue: 155000 },
];

export const MOCK_TEMPLATES: NotificationTemplate[] = [
  {
    id: 'T1',
    type: 'Email',
    trigger: 'Due Soon (T-3 Days)',
    subject: 'Action Required: ISP Renewal for {location_name}',
    body: 'Dear Manager,\n\nThis is a reminder that the internet plan for {location_name} is due for renewal on {due_date}. The plan amount is ₹{amount}.\n\nPlease ensure the recharge is initiated to avoid downtime.\n\nRegards,\nIT Team',
    variables: ['location_name', 'due_date', 'amount'],
    lastUpdated: '2026-03-20',
  },
  {
    id: 'T2',
    type: 'WhatsApp',
    trigger: 'Overdue (Day 0)',
    body: '⚠️ *URGENT:* ISP plan for *{location_name}* has EXPIRED today. Please recharge immediately to restore connectivity. Amount: ₹{amount}.',
    variables: ['location_name', 'amount'],
    lastUpdated: '2026-03-25',
  },
  {
    id: 'T3',
    type: 'Push',
    trigger: 'Payment Success',
    body: 'Payment of ₹{amount} for {location_name} was successful. Next due date: {next_due_date}.',
    variables: ['amount', 'location_name', 'next_due_date'],
    lastUpdated: '2026-03-28',
  }
];

